name: Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: workaround dotnet restore
      # https://github.com/actions/virtual-environments/issues/3038#issuecomment-816450054 
      run: Remove-Item $env:APPDATA\NuGet\NuGet.Config
    - name: Restore dependencies
      run: dotnet restore
    - name: Rename dev snk file
      run: Rename-Item UmaMadoManager.Windows/keyfile.dev.snk keyfile.snk
    - name: Build
      run: dotnet publish -c Release UmaMadoManager.Windows
    - name: Upload built exe
      uses: actions/upload-artifact@v2
      with:
        name: UmaMadoManager.Windows
        path: UmaMadoManager.Windows/bin/Release/net5.0-windows/win-x86/publish

  test: # Todo impl
    needs: build
    runs-on: windows-latest # Windows 7とかのテスト走らせられるやつなかった…

    steps:
      - uses: actions/checkout@v2
      - name: Download built exe
        uses: actions/download-artifact@v2
        with:
          name: UmaMadoManager.Windows
